language: objective-c
xcode_project: PrettyOkayKit.xcodeproj
xcode_scheme: PrettyOkayKit
osx_image: xcode8
before_install: true
install: true
git:
  submodules: false
script:
  - /usr/local/bin/carthage bootstrap --platform iOS --no-use-binaries
  - xcodebuild -project PrettyOkayKit.xcodeproj -scheme PrettyOkayKit
